spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: manager
    url: jdbc:mysql://localhost:3306/his
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #smtp properties


  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: bheemesh2jetty@gmail.com
    password: twts mewd jfmw nigq
    port: '587'
